bank_multipliers = {
'aavas': 1.1, 
'aditya birla housing finance': 1.1, 
'anand rathi global finance ltd': 1.1, 
'au small finance bank ltd': 1.1, 
'axis bank': 1.15, 
'axis finance': 1.1, 
'bandhan bank': 1.1, 
'bank of baroda': 1.1, 
'bank of india': 1.1, 
'bank of maharashtra': 1.1, 
'can fin homes ltd': 1.1, 
'canara bank ltd': 1.1, 
'capri global': 1.1, 
'central bank of india': 1.1, 
'centrum housing finance limited': 1.1, 
'cholamandalam': 1.1, 
'citi bank': 1.15, 
'citi finance': 1.1, 
'city union bank ltd': 1.1, 
'dbs': 1.1, 
'dcb': 1.1, 
'deutsche bank': 1.15, 
'dhanlaxmi bank': 1.1, 
'equitas small finance bank': 1.1, 
'fed bank financial services ltd': 1.1, 
'federal bank ltd': 1.1, 
'fullerton': 1.1, 
'gic housing finance': 1.1, 
'hdfc ltd': 1.15, 
'hdfc': 1.15, 
'hero hfl': 1.1, 
'home first finance': 1.1, 
'hsbc bank': 1.15, 
'icici bank': 1.15,
'icici': 1.15,
'icici hfl': 1.1, 
'idbi bank ltd': 1.1, 
'idfc bank': 1.1, 
'iifl': 1.1, 
'indiabulls hfl': 1.1, 
'indian bank': 1.1, 
'indian overseas bank': 1.1, 
'indusind bank': 1.15, 
'jana small finance bank': 1.1, 
'karnataka bank ltd': 1.1, 
'karur vysya bank ltd': 1.1, 
'kotak mahindra bank': 1.15, 
'l&t finance/ l&t housing finance': 1.1, 
'lakshmi vilas bank': 1.1, 
'lic hfl': 1.15, 
'muthoot housing finance': 1.1, 
'piramal hfl/ dhfl': 1.1, 
'pnb housing finance': 1.15, 
'punjab & sind bank': 1.1, 
'punjab national bank': 1.1, 
'rbl': 1.1, 
'saraswat co-op bank': 1.1, 
'sbfc': 1.1, 
'shriram housing finance': 1.1, 
'south indian bank ltd': 1.1, 
'standard chartered': 1.15, 
'state bank of india': 1.15,
'sbi': 1.15,
'sundaram hfl': 1.1, 
'svc co op bank': 1.1, 
'tamilnad mercantile bank': 1.1, 
'tata capital / hfl': 1.1, 
'uco bank': 1.1, 
'ujjivan small finance bank ltd': 1.1, 
'union bank of india': 1.1, 
'yes bank ltd': 1.1,
'yes bank': 1.1
}
